#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# early exit
  [[ ! -f "$DOKKU_ROOT/VHOST" ]] && exit 0

# save stdout outlet
  exec 4<&1

# disable stdout & stderr
  exec 1>/dev/null
  exec 2>/dev/null


APP="$1"; SUBDOMAIN="$2"; VHOST="$3";
TMPDIR=$(mktemp -d)

cleanup() {
  rm -rf "$TMPDIR" 2> /dev/null || true;
}
trap cleanup EXIT

if [[ "$APP" == *.* ]] && [[ "$SUBDOMAIN" == "$APP" ]]; then
  autohostname="${APP/\//-}"
else
  autohostname="${APP/\//-}.$VHOST"
fi

cd "$TMPDIR" && git clone -q "$DOKKU_ROOT/$APP" repo > /dev/null 2>&1

appvhost=''

if [[ -f "$TMPDIR/repo/VHOST" ]]; then
  appvhost="$(cat "$TMPDIR/repo/VHOST" 2> /dev/null)"
fi


# return regular stdout
  exec 1<&4

# appends dokku generated hostname to user hostnames,               removes comments,     rm empty lines, lowercase,           unique lines
  printf "%s\n" "$autohostname" "$appvhost" | sed 's:^\s*#.*$::g' | grep -v '^$' | tr '[:upper:]' '[:lower:]' | awk '!x[$0]++';
