#!/usr/bin/env bash

# Hook to add a list of hosts specified in VHOST file.
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname $0)/../common/functions"

dokku_log_info1 "container VHOST"
# exit if dokku VHOST is not present
[[ ! -f "$DOKKU_ROOT/VHOST" ]] && dokku_log_warn "dokku doesn't manage VHOSTS" && exit 0;

[[ -f "$DOKKU_ROOT/ENV" ]] && source $DOKKU_ROOT/ENV
[[ -f "$DOKKU_ROOT/$APP/ENV" ]] && source $DOKKU_ROOT/$APP/ENV

APP="${1}";
CONTAINERID="$(cat ${DOKKU_ROOT}/${APP}/CONTAINER)";
OLDAPPVHOST="${DOKKU_ROOT}/${APP}/APPVHOST";
VHOSTFILE="${DOKKU_ROOT}/${APP}/VHOST";
ADDED=0; REMOVED=0;


[[ ! -f $OLDAPPVHOST ]] && touch $OLDAPPVHOST;

[[ ! -r $OLDAPPVHOST ]] && dokku_log_fail "cant read $OLDAPPVHOST";
[[ ! -w $OLDAPPVHOST ]] && dokku_log_fail "cant write to $OLDAPPVHOST";
[[ ! -r $VHOSTFILE ]] && dokku_log_fail "cant read $VHOSTFILE";
[[ ! -w $VHOSTFILE ]] && dokku_log_fail "cant write to $VHOSTFILE";

TMPDIR=$(mktemp -d /tmp/VHOST.XXXXX);
docker cp $CONTAINERID:/app/VHOST $TMPDIR 2> /dev/null || true
if [[ ! -s "${TMPDIR}/VHOST" ]] ; then
  dokku_log_verbose "VHOST file not found in container. skipping."
  rm -rf $TMPDIR || true;
  exit 0
else
  dokku_log_verbose "VHOST file found in container"
  FILENAME="${TMPDIR}/VHOST"
  cat "$FILENAME" | tr '[A-Z]' '[a-z]' | sort -u > ${TMPDIR}/SORTED;
  NEWAPPVHOST="${TMPDIR}/SORTED"

  cleanup() {
    dokku_log_verbose "removing VHOST file copied from container ..."
    rm -rf $TMPDIR || true;
  }
  trap cleanup EXIT
fi

while read ADDURL; do
  # Ignore empty lines and lines starting with #
  [[ -z "$ADDURL" || "$ADDURL" =~ ^# ]] && continue
  if ! grep -Fxq "$ADDURL" "$VHOSTFILE"; then
    dokku_log_verbose "    add URL: $ADDURL";
    echo $ADDURL >> $VHOSTFILE;
    ((ADDED++));
  fi
done < <(comm -13 $OLDAPPVHOST $NEWAPPVHOST)

while read RMURL; do
  # Ignore empty lines and lines starting with #
  [[ -z "$RMURL" || "$RMURL" =~ ^# ]] && continue
  if grep -Fxq "$RMURL" "$VHOSTFILE"; then
    dokku_log_verbose "    remove URL: $ADDURL";
    sed -i "/^${RMURL}$/d" "$VHOSTFILE";
    ((REMOVED++));
  fi
done < <(comm -23 $OLDAPPVHOST $NEWAPPVHOST)

if [[ $ADDED -gt 0 || $REMOVED -gt 0 ]]; then
  STATUS='[CHANGES] ';
  [[ $ADDED   -gt 0 ]] && STATUS+="added: $ADDED ";
  [[ $REMOVED -gt 0 ]] && STATUS+="removed: $REMOVED ";
  dokku_log_verbose $STATUS;
else
  dokku_log_verbose "no changes made."
fi

exit 0